import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from db.database import AsyncSessionLocal
from crawler.news_crawler import run_news_crawl
from api.news import get_causal_events

async def test():
    print("Running news crawl (fetches media with curl_cffi, runs Event Pipeline)...")
    async with AsyncSessionLocal() as session:
        result = await run_news_crawl(session)
        print("News Crawl Result:", result)
        
        print("\nChecking Causal Events generated by LLM...")
        events = await get_causal_events(limit=5, db=session)
        for e in events:
            print(f"[{e.importance}/10] {e.event_title} ({e.country})")
            print(f"  Bullish: {e.bullish_stocks}")
            print(f"  Bearish: {e.bearish_stocks}")
            print(f"  Sectors: {e.affected_sectors}")

asyncio.run(test())
